{
  description = "NixOS cluster configuration with K3s using flakes";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
    nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";

    # Sops integration
    sops-nix.url = "github:Mic92/sops-nix";
    sops-nix.inputs.nixpkgs.follows = "nixpkgs";

    # RustFS object storage
    rustfs.url = "github:rustfs/rustfs-flake";
    rustfs.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, nixpkgs-unstable, sops-nix, rustfs, ... }@inputs:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };

      # Overlay to add unstable packages when needed
      overlays = [
        (final: prev: {
          unstable = import nixpkgs-unstable {
            inherit system;
            config.allowUnfree = true;
          };
        })
      ];

      # Config common to all hosts
      commonModules = [
        sops-nix.nixosModules.sops
        ./modules/core
        { nixpkgs.overlays = overlays; }
        # Hardware config lives alongside the flake (copied/generated by update.sh)
        ./hardware-configuration.nix
      ];

      # Helper to define a host with minimal boilerplate
      mkHost = name: extraModules:
        nixpkgs.lib.nixosSystem {
          inherit system;
          specialArgs = { inherit inputs; };
          modules = commonModules ++ [ ./hosts/${name} ] ++ extraModules;
        };

    in {
      nixosConfigurations = {
        flo    = mkHost "flo"    [];
        rob    = mkHost "rob"    [];
        bob    = mkHost "bob"    [];
        ping   = mkHost "ping"   [];
        oogway = mkHost "oogway" [];
        shifu  = mkHost "shifu"  [];
        monkey = mkHost "monkey" [];
      };

      # Development shell with cluster management tools
      devShells.${system}.default = pkgs.mkShell {
        packages = with pkgs; [
          sops
          age
          ssh-to-age
          nixos-rebuild
        ];
        shellHook = ''
          echo "ClusterConfig dev shell loaded"
          echo "  sops secrets/secrets.yaml  — edit secrets"
          echo "  nix flake check            — validate config"
        '';
      };

      # Formatter for `nix fmt`
      formatter.${system} = pkgs.nixpkgs-fmt;
    };
}
